databases:
  - name: vcardpro-db
    databaseName: vcardpro
    user: vcardpro
    plan: free
    region: oregon # Or your preferred region (e.g., frankfurt, ohio, singapore)

services:
  - type: web
    name: vcardpro-web
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: VCardPro
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://vcardpro-web.onrender.com"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: vcardpro-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: vcardpro-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: vcardpro-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: vcardpro-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: vcardpro-db
          property: password
      - key: APP_KEY
        value: "base64:/VR7itPRMggN281EBagG3/F3YV+RaTb8u973wcwHc/U="
